service:
  name: Intobox
  mail: info@intobox.in
  facebook_application_name: intobox
  host_name: intobox.in
  full_uri: https://intobox.in
facebook:
  invitation:
    redirect_uri: https://intobox.in/home
    link: https://intobox.in
dropbox:
  file_size_limit: 157286400
  app_folder_name:
    default: アプリ
    JA: アプリ
    US: Apps
send_directory: Intobox
notify:
  from: notice@intobox.in
  to:
    error: error@intobox.in
    withdrawal: info@intobox.in
growth:
  service_name: web_app
black_list:
  - exe
  - com
  - pif
  - bat
  - scr
database:
  users:
    state:
      valid: 1
    delete_reason:
      - もうIntoboxを使う必要がない
      - Intoboxより良いサービスを見つけた
      - 使いにくかった
      - 問題が発生して使えなかった
      - 必要な機能がなかった
  transfer_histories:
    state:
      sending: 1
      success: 2
      error: 3
