service:
  host_name: intobox.in
facebook:
  invitation:
    redirect_uri: https://intobox.in/home
oauth:
  facebook:
    redirect_uri: https://intobox.in/auth/facebook/callback
  dropbox:
    redirect_uri: https://intobox.in/auth/dropbox_oauth2/callback
