service:
  host_name: staging.intobox.in
facebook:
  invitation:
    redirect_uri: http://staging.intobox.in/home
oauth:
  facebook:
    redirect_uri: https://staging.intobox.in/auth/facebook/callback
  dropbox:
    redirect_uri: https://staging.intobox.in/auth/dropbox_oauth2/callback
